info: 'Check whether there is a disk hole issue.'
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: "select sum(DATA_SIZE) as da from oceanbase.CDB_OB_TABLET_REPLICAS  group by tenant_id  ORDER BY da DESC limit 1;"
      result:
        set_value: not_ACTIVE
        report_type: execution
        verify_type: equal
        verify: 0
        err_msg: '[not warning] the DATA_SIZE is not 0 . need check sum(REQUIRED_SIZE)/sum(DATA_SIZE)'
    - type: sql
      sql: "select sum(REQUIRED_SIZE)/sum(DATA_SIZE) as da from oceanbase.CDB_OB_TABLET_REPLICAS  group by tenant_id  ORDER BY da DESC limit 1;"
      result:
        set_value: not_ACTIVE
        report_type: warning
        verify_type: max
        verify: 1000
        err_msg: 'There may be a problem of disk holes.Please check oceanbase.CDB_OB_TABLET_REPLICAS  group by tenant_id  ORDER BY da DESC '
  - version: "[*,3.2.0]"
    steps:
      - type: sql
        sql: "select sum(REQUIRED_SIZE)/sum(DATA_SIZE) as da from oceanbase.__all_virtual_meta_table  group by tenant_id  ORDER BY da DESC limit 1;"
        result:
          set_value: not_ACTIVE
          report_type: warning
          verify_type: max
          verify: 1000
          err_msg: 'There may be an issue with empty disks'



