info_en: "[server info]"
info_cn: "[server 信息展示]"
command: obdiag display scene run --scene=observer.server_info
task:
  - version: "[4.0.0.0, *]"
    steps:
      - type: sql
        sql: "select * from oceanbase.__all_server;"
        global: true
