info: 'Check when sysbench run , cluster info about cpu'
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: "
SELECT TENANT_ID
FROM oceanbase.DBA_OB_TENANTS
WHERE TENANT_TYPE='USER' limit 1;"
      result:
        set_value: tenant_id
        verify: '[ -n "${tenant_id}" ]'
        err_msg: "tenant_id is null . Please check your tenant without sys"
    - type: sql
      sql: 'select VALUE from oceanbase.GV$OB_PARAMETERS where Name="cpu_quota_concurrency"
                                           and TENANT_ID="#{tenant_id}"
                                           and SVR_IP="#{remote_ip}" limit 1;'
      result:
        set_value: cpu_quota_concurrency
    - type: sql
      sql: 'SELECT  t3.MAX_CPU FROM OCEANBASE.DBA_OB_TENANTS t1,OCEANBASE.DBA_OB_UNITS t2,OCEANBASE.DBA_OB_UNIT_CONFIGS t3,OCEANBASE.DBA_OB_RESOURCE_POOLS t4
where t1.tenant_id = t4.tenant_id
  and t1.tenant_id="#{tenant_id}"
  AND t4.resource_pool_id=t2.resource_pool_id
  AND t4.unit_config_id=t3.unit_config_id
and t2.svr_ip="#{remote_ip}"

ORDER BY t1.tenant_name limit 1;'
      result:
        set_value: max_cpu

    - type: ssh
      ssh: "echo #{max_cpu} | bc -l | cut -d '.' -f1"
      result:
        set_value: max_cpu
    - type: ssh
      ssh: "cat #{remote_home_path}/run/observer.pid"
      result:
        set_value: observer_pid
    - type: ssh
      ssh: "top -d 2 -H -b -n1 -p  #{observer_pid} | grep #{tenant_id} | awk '{total+=$9}END{printf \"%.0f\",total}'"
      result:
        set_value: tenant_cpu_used
    - type: ssh
      ssh: 'echo $((#{tenant_cpu_used} * 100 / #{max_cpu} / #{cpu_quota_concurrency}))'
      result:
        set_value: result
        verify_type: min
        verify: 89
        report_type: warning
        err_msg: "tenant_cpu_used /max_cpu * cpu_quota_concurrency <90% ,it is #{result}. remote_ip is #{remote_ip}. tenant id is #{tenant_id}. max_cpu is #{max_cpu}. tenant_cpu_used is #{tenant_cpu_used}. cpu_quota_concurrency is #{cpu_quota_concurrency}."

    - type: ssh
      ssh: 'echo $((#{tenant_cpu_used} * 100 / #{max_cpu} / #{cpu_quota_concurrency}))'
      result:
        set_value: result
        verify_type: min
        verify: 89
        report_type: execution
        err_msg: "tenant_cpu_used /max_cpu * cpu_quota_concurrency <90% ,it is #{result}. remote_ip is #{remote_ip}. tenant id is #{tenant_id}. max_cpu is #{max_cpu}. tenant_cpu_used is #{tenant_cpu_used}. cpu_quota_concurrency is #{cpu_quota_concurrency}."
    - type: ssh
      ssh: "top -H -b -n1 -p  #{observer_pid} | grep #{tenant_id}   | awk -v threshold=0.9 -F' ' 'NR > 7 && $9 > threshold { if (length(names)>0) names=names\",\"; names=names$12 } END{print names}'"
      result:
        set_value: thread
        verify: '[ -z "${thread}" ]'
        report_type: warning
        err_msg: "remote_ip is #{remote_ip} . tenant id is #{tenant_id}. over 0.9c thread is #{thread}"



        
    

