
info: "Check if there are files in the clog folder that do not belong to the observer"
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: ssh
      ssh: 'find #{remote_redo_dir}/ -name "clog"'
      result:
        set_value: log_dir_path
        verify: '[ -n "${log_dir_path}" ]'
        err_msg: "log_dir_path is null . Please check your nodes.redo_dir need absolute Path"
    - type: ssh
      ssh: "find #{log_dir_path} -type f -name '*[^0-9]*'  ! -name  '*.tmp' ! -name '*.flashback' ! -name 'meta'"
      result:
        set_value: files
        verify: '[ -z "${files}" ]'
        err_msg: "Users are not allowed to modify or create in the clog folder, It will be causing observer startup failure. Files need be checked: #{files}"

