info: 'Check the flags of cpu'
task:
  - steps:
      - type: ssh
        ssh: "lscpu |grep Flags"
        result:
          set_value: cpu_flags
          verify: " [[ $cpu_flags == *avx2* ]] "
          err_msg: 'observer need cpu support avx2. If the cpu is not support avx2, observer will be crash.'


