info: 'Check whether Error 4012  is reported when enable_sql_audit is set to True.'
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_PARAMETERS where NAME="enable_sql_audit" and VALUE<>"True" ;'
      result:
        set_value: sql_audit
        # report_type: warning
        verify_type: equal
        verify: 0
        err_msg: 'Unable to proceed because enable_sql_audit is set to False'
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_SQL_AUDIT where RET_CODE ="-4012";'
      result:
        set_value: err_4012
        report_type: warning
        verify_type: max
        verify: 100
        err_msg: 'number of sql_error_4012 is #{err_4012}'


