info: "Check if there is a problem with clog disk full"
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'SELECT  GROUP_CONCAT(DISTINCT u.tenant_id) FROM oceanbase.gv$ob_units u  JOIN (    SELECT SVR_IP, SVR_PORT, TENANT_ID, value/100 AS value  FROM oceanbase.GV$OB_PARAMETERS   WHERE name = "log_disk_utilization_threshold") as c     ON u.SVR_IP = c.SVR_IP AND u.SVR_PORT = c.SVR_PORT AND u.TENANT_ID = c.TENANT_ID WHERE u.LOG_DISK_IN_USE > u.LOG_DISK_SIZE * c.value;'
      result:
        set_value: tenant_ids
        verify: '[ -z "$tenant_ids" ]'
        err_msg: "The following tenants have experienced clog disk full: #{tenant_ids}. Please check by obdiag rca --scene=clog_disk_full "
