info: "Check whether there is a deadlock."
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select count(0) from oceanbase.DBA_OB_DEADLOCK_EVENT_HISTORY;'
      result:
        set_value: deadlocks_nu
        verify_type: equal
        report_type: warning
        verify: 0
        err_msg: "There is a deadlock. Please check on the oceanbase.DBA_OB_DEADLOCK_EVENT_HISTORY"