info: 'To detect dependent software, refer to: https://www.oceanbase.com/docs/enterprise-oceanbase-ocp-cn-1000000000125643'
task:
  - steps:
    - type: ssh
      ssh: 'systemctl is-active --quiet firewalld  && echo "Running" || echo "Not Running"'
      result:
        set_value: firewalld_switch
        report_type: warning
        verify: '[ "Not Running" == "${firewalld_switch}" ]'
        err_msg: 'firewalld is #{firewalld_switch} ,It is recommended to disable firewalld or add allow rules for each service in the OceanBase cluster to avoid firewall interception.'
    - type: ssh
      ssh: 'systemctl is-active --quiet crond  && echo "Running" || echo "Not Running"'
      result:
        set_value: crond_switch
        report_type: warning
        verify: '[ "Running" == "${crond_switch}" ]'
        err_msg: 'crond is #{crond_switch}.It is recommended to enable it, mainly for setting up scheduled tasks and providing related operation and maintenance capabilities.'
    - type: ssh
      ssh: 'cat /sys/kernel/mm/transparent_hugepage/enabled |grep "[never]"'
      result:
        set_value: transparent_hugepage_switch
        report_type: warning
        verify: '[ -n "${transparent_hugepage_switch}" ]'
        err_msg: 'transparent_hugepage need retrun "[never]". Now , it is null.'