info: 'Check task opt stat gather history.'
task:
  - version: "[4.2.0.0,*]"
    steps:
    - type: sql
      sql: 'SELECT GROUP_CONCAT(DISTINCT TENANT_ID)  
FROM   oceanbase.__all_tenant t
WHERE  NOT EXISTS(SELECT 1
                  FROM   oceanbase.__all_virtual_task_opt_stat_gather_history h
                  WHERE  TYPE = 1
                  AND start_time > date_sub(now(), interval 1 day)
                  AND h.tenant_id = t.tenant_id);'
      result:
        set_value: failed_scheduler_tenant_id
        verify: '[ -z "${failed_scheduler_tenant_id}" ]'
        err_msg: "The collection of statistical information related to tenants has issues.. Please check the tenant_ids: #{failed_scheduler_tenant_id}"