info: 'Check observer version . Some versions of observers are not recommended'
task:
  - steps:
    - type: ssh
      ssh: "export LD_LIBRARY_PATH=#{remote_home_path}/lib && #{remote_home_path}/bin/observer --version 2>&1  |  grep -oP 'REVISION: \\K\\d+'"
      result:
        set_value: observer_version
    - type: ssh
      ssh: '[ "#{observer_version}" = "100000192023032010" ] && echo "0" || echo "1"'
      result:
        set_value: result
        verify_type: equal
        verify: 1
        err_msg: 'the version is 100000192023032010 , the observer is not recommended'
    - type: ssh
      ssh: '[ "#{observer_version}" = "103000072023081111" ] && echo "0" || echo "1"'
      result:
        set_value: result
        verify_type: equal
        verify: 1
        err_msg: 'the version is 103000072023081111 , the observer is not recommended'
    - type: ssh
      ssh: '[ "#{observer_version}" = "104000032023092120" ] && echo "0" || echo "1"'
      result:
        set_value: result
        verify_type: equal
        verify: 1
        err_msg: 'the version is 104000032023092120 , the observer is not recommended'



