info: 'Check observer version . Some versions of observers are not recommended'
task:
  - steps:
    - type: ssh
      ssh: 'export LD_LIBRARY_PATH=#{remote_home_path}/lib && #{remote_home_path}/bin/observer --version 2>&1  | grep "(OceanBase"'
      result:
        set_value: observer_version
        verify: '[[ ! "#{observer_version}" == *"3.1."* ]] || [[ ! "#{observer_version}" == *"CE"* ]]'
        err_msg: 'Starting from June 30, 2024, OceanBase Database Community Edition V3.1.x will no longer receive any bug fixes or version updates.Please upgrade as soon as possible'




