name: build package

on:
  pull_request:
    branches: "*"
  push:
    branches: "*"
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run-with-observer:
    name: run-with-observer
    runs-on: ubuntu-latest
    container:
      image: "oceanbase/oceanbase-ce:4.2.5.3-103000022025033117"
    steps:
    - name: install obdiag
      run: |
        set -e
        yum install -y wget \
          && wget https://obbusiness-private.oss-cn-shanghai.aliyuncs.com/download-center/opensource/obdiag/v3.2.0/oceanbase-diagnostic-tool-3.2.0-52025031411.el7.x86_64.rpm \
          && yum install -y ./oceanbase-diagnostic-tool-*.rpm
    - name: run obdiag checks
      run: |
        ls ~/
        obdiag check list
          
