name: build package

on:
  pull_request:
    branches: "*"
  push:
    branches: "*"
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run-with-observer:
    name: run-with-observer
    runs-on: ubuntu-latest
    container:
      image: "oceanbase/oceanbase-ce:4.3.0"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: install obdiag
      run: |
        set -e
        yum install -y wget
        wget https://obbusiness-private.oss-cn-shanghai.aliyuncs.com/download-center/opensource/obdiag/v3.2.0/oceanbase-diagnostic-tool-3.2.0-52025031411.el7.x86_64.rpm
        yum install -y ./oceanbase-diagnostic-tool-*.rpm
        cp example/mini.yml /root/.obdiag/config.yml
        cp -r /root/.obdiag /github/home
        ps -aux |grep obd
        cat /root/.obd/log/obd
        sh workflow_data/wait_observer_run.sh
    - name: run obdiag checks
      run: |
        ls ~/
        obdiag check list
        obdiag check run
          
